### ISSUE TITLE
Example where main text body not extracted

### ISSUE THREAD

**Issue by dewey** [philipjkim/goreadability#8]
Not sure if that's helpful, just thought I'll dump this here as an reproducible example.

```
package main

import (
	"fmt"

	"github.com/mmcdole/gofeed"
	readability "github.com/philipjkim/goreadability"
)

func main() {
	fp := gofeed.NewParser()
	feed, err := fp.ParseURL("https://roadsandkingdoms.com/feed/")
	if err != nil {
		return
	}
	opt := readability.NewOption()
	opt.DescriptionExtractionTimeout = 4000

	opt.ImageRequestTimeout = 3000
	for _, i := range feed.Items {
		fmt.Println(i.Link)
		content, err := readability.Extract(i.Link, opt)
		if err != nil {
			return
		}
		fmt.Println(content.Title)
		fmt.Println(content.Description)
		break
	}
}
```

Output:
```
Desktop|⇒ go run thing.go
https://roadsandkingdoms.com/2018/rk-insider-lets-talk-about-brazil/
R&K Insider: Let's talk about Brazil
 Frustration, despair, and heightened risk: those are the common themes in conversations with friends and colleagues who have been covering the protests in Gaza and the West Bank.
Desktop|⇒
```

https://github.com/mauidude/go-readability works correctly so I'm going to switch to that one for now.

**Comment by philipjkim** [comment]
@dewey Sorry for late response. I found that the traditional arc90's readability rule does not extract the body content of the URL you've tested (when using default option values). To enhance the accuracy of title/description/image extraction, I added to look up OpenGraph tags and use values if exists, and increased goreadability version to `2.0.0`. Nowadays most of webpages contains og tags, so I thought it'll be more efficient and accurate to use og tags.

I'm not sure adding this feature will solve this issue. Please leave any thoughts about that if you don't mind. Thanks!
